filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /home/ubuntu/amir.log
...<CODE>...
output.logstash:
  # The Logstash hosts
  hosts: ["37.32.15.140:5044"]
  protocol: "https"
  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  ssl.certificate_authorities: ["/home/ubuntu/beat/ca.crt"]
  # Certificate for SSL client authentication
  ssl.certificate: "/home/ubuntu/beat/beat.crt"
  # Client Certificate Key
  ssl.key: "/home/ubuntu/beat/beat.key"
